version: '3'

services:
  nest-app:
    build:
      context: ./ticket_booking_app
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=dpg-chsdqmu7avjdbih7tnv0-a.singapore-postgres.render.com
      - POSTGRES_PORT=5432
      - POSTGRES_USER=ankit
      - POSTGRES_PASSWORD=kmJlGzKvAUdJJ6jCwrbwpqwEiFY3wdSN
      - POSTGRES_DB=movie_ticket
    volumes:
      - ./ticket_booking_app:/ticket_booking_app

