version: '3'

services:
  nest-app:
    build:
      context: ./ticket_booking_app
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    depends_on:
      - db
    volumes:
      - ./ticket_booking_app:/ticket_booking_app

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
